### ISSUE TITLE
Need the web.config

### ISSUE THREAD

**Issue by aarongustafson** [habilelabs/english-sikho-lite#1]
https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by morwalz** [comment]
Hi, I committed on config file. Please check. 
If we still can not run on iis-node then please run on simple node installation this will work. 
we also deployed it on 
http://lite.englishsikho.com/

please check this.

**Comment by molant** [comment]
@morwalz we fixed your site for the contest. As an FYI, the web.config you can find in the contest rules for node works: https://a-k-apart.com/webconfigs/web.config.node.txt
You just need to replace index.js with server.js.

**Comment by morwalz** [comment]
thank you so much. I will check how you done it.
